# Generated by Django 5.0.6 on 2024-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsession', '0002_remove_labsession_unique_course_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
