# Generated by Django 5.0.6 on 2024-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_courses_programs_alter_courses_staff'),
        ('labsession', '0003_alter_labsession_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labsession',
            unique_together={('course', 'order')},
        ),
        migrations.AlterField(
            model_name='labsession',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='labsession',
            unique_together={('course', 'name'), ('course', 'order')},
        ),
    ]
