# Generated by Django 5.0.6 on 2024-08-20 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsession', '0004_alter_labsession_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentLabSessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('lab_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='labsession.labsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'lab_session')},
            },
        ),
    ]
