# Generated by Django 5.0.6 on 2024-06-18 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0002_alter_programs_program_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(error_messages={'unique': 'A course with that name already exists.'}, max_length=255, unique=True)),
                ('programs', models.ManyToManyField(related_name='courses', to='program.programs')),
                ('staff', models.ManyToManyField(limit_choices_to={'user_type': 'staff'}, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
