# Generated by Django 5.0.6 on 2024-07-15 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('program', '0002_alter_programs_program_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='courses', to='program.programs'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'staff'}, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
