# Generated by Django 5.0.6 on 2024-06-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='user_type',
        ),
    ]
