# Generated by Django 5.0.6 on 2024-07-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_staff_course_remove_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='program',
        ),
    ]
