# Generated by Django 5.0.6 on 2024-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(error_messages={'unique': 'A user with that name already exists.'}, max_length=255, unique=True)),
                ('program_lenght', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
