# Generated by Django 5.0.6 on 2024-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_name',
            field=models.CharField(error_messages={'unique': 'A program with that name already exists.'}, max_length=255, unique=True),
        ),
    ]
